export const ANALYTICS = {
  SELECT_FORMAT_TITLE: 'SELECT_FORMAT_TITLE',
  SELECT_FORMAT_DIALOG_DESCRIPTION: 'SELECT_FORMAT_DIALOG_DESCRIPTION',
  START_EXPORTING: 'START_EXPORTING',
  EXPORTING_DONE: 'EXPORTING_DONE',
  LAST_THREE_MONTHS_LABEL: 'LAST_THREE_MONTHS_LABEL',
};
